# Movement
TARGET_SPEED = 12.0
STEER_LIMIT  = 0.5
STEER_GAIN   = 0.002
STEER_SMOOTH = 0.7

# Lighting
DARK_THRESHOLD = 39.0

# Car center
CAR_CENTER_X = 560

# Lane
NUM_MIDLINE_SAMPLES   = 15
CANNY_LOW             = 50
CANNY_HIGH            = 140
MORPH_KERNEL_SIZE     = 5
HOUGH_THRESHOLD       = 40
HOUGH_MIN_LINE_LENGTH = 40
HOUGH_MAX_LINE_GAP    = 35
ALPHA_SMOOTH_MIDLINE = 0.7

# Cropping
CROP_RATIO = 0.625